esphome:
#  esphomelib_version:
#    branch: dev
  name: chamberssign
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
        - light.turn_off:
            id: chamberssign_light
switch:
  - platform: restart
    name: "Chambers Sign Restart"
light:
  - platform: fastled_clockless
    chipset: WS2813
    pin: D4
    num_leds: 17
    rgb_order: GRB
    name: "Chambers Sign"
    id: chamberssign_light
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: "Rainbow Effect With Custom Values"
          speed: 50
          width: 100
binary_sensor:
  - platform: gpio
    pin: D7
    name: "Chambers Sign Motion"
    device_class: motion

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.10.81
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.10.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

mqtt:
  broker: !secret MQTT_broker
  username: !secret MQTT_username
  password: !secret MQTT_password
  discovery: True
  reboot_timeout: 1h

# Enable logging
logger:

ota:

web_server:
  port: 80
