esphome:
  name: hallway
  platform: ESP8266
  board: nodemcuv2

binary_sensor:
  - platform: gpio
    pin: D7
    name: "Hallway Motion"
    device_class: motion
    filters:
      - delayed_off: 10ms
      - delayed_on: 10ms

switch:
  - platform: restart
    name: "Hallway Restart"

sensor:
  - platform: dht
    pin: D3
    temperature:
      name: "Hallway Temperature"
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Hallway Humidity"
    update_interval: 60s
    model: DHT22

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.10.84
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.10.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

mqtt:
  broker: !secret MQTT_broker
  username: !secret MQTT_username
  password: !secret MQTT_password
  discovery: True
  reboot_timeout: 1h

# Enable logging
logger:

ota:

#web_server:
#   port: 80


