esphome:
#  esphome_core_version:
#    branch: dev
  name: stairs
  platform: ESP8266
  board: nodemcuv2
  on_shutdown:
    then:
        - light.turn_off:
            id: stairs_light
  on_boot:
    then:
        - light.turn_on:
            id: stairs_light
            brightness: 100%
            white: 1%
        - light.turn_off:
            id: stairs_light
switch:
  - platform: restart
    name: "Stairs Restart"
light:
  - platform: neopixelbus
    variant: SK6812
    pin: D4
    num_leds: 231
    type: GRBW
    color_correct: [80%, 80%, 80%,80%]
    name: "Stairs Lights"
    id: stairs_light
    method: ESP8266_UART1
    effects:
      - addressable_rainbow:
          width: 300
      - addressable_rainbow:
          name: "Rainbow Effect With Custom Values"
          speed: 50
          width: 300
      - random:
      - strobe:
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms
      - flicker:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.10.85
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.10.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

mqtt:
  broker: !secret MQTT_broker
  username: !secret MQTT_username
  password: !secret MQTT_password
  discovery: True
  reboot_timeout: 1h

# Enable logging
logger:

ota:

web_server:
  port: 80
